version: '2'

services:
#  nginx:
#    build: ./nginx
#    ports:
#      - "8080:80"
#      - "443:443"
#    volumes:
#      - ../:/var/www/html
#      - ../:/usr/share/nginx/html
#    container_name: nginx
#
#  data:
#    image: busybox
#    volumes:
#      - ./misc/data:/var/lib/mysql

#  mysql:
#    image: mysql:5.7
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: mysql_database
#      MYSQL_USER: mysql_user
#      MYSQL_PASSWORD: mysql_pw
#    ports:
#      - "13306:3306"
#    volumes_from:
#      - data
#    volumes:
#      - ../application/initial.sql:/docker-entrypoint-initdb.d/initial.sql
#    container_name: mysql

  ruby:
    build:
      context: ./ruby
      args:
      # docker build時にdockerfileへ透過させる環境変数
        - http_proxy
        - https_proxy
        - no_proxy
#    links:
#      - mysql
#    environment:
#      DATABASE_HOST: 'mysql'
#      DATABASE_NAME: 'mysql_database'
#      DATABASE_USER: 'mysql_user'
#      DATABASE_PASSWORD: 'mysql_pw'
    working_dir: '/usr/src/app'
    volumes:
      - ./ruby/www:/usr/src/app
    command: 'ruby main.rb'
    ports:
      - "4567:4567"
    environment:
    # proxy系の環境変数はホスト側の設定を参照
      - http_proxy
      - https_proxy
      - no_proxy
    container_name: ruby2
